spring:
  application:
    name: rouna-gateway # 应用名
#  cloud:
#      config:
#        enabled: true
#        profile: dev
#        label: master
#        discovery:
#          enabled: true
#          service-id: Rouna-Config
server:
  port: 8768 #Zuul Server的端口号
eureka:
 instance:
   prefer-ip-address: true
   instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
 client:
  healthcheck:
   enabled: true
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

zuul:
  routes:
#    api-contract: # 其中api-contract是路由名称，可以随便定义，但是path和service-id需要一一对应
#      path: /system/**
#      service-id: ROUNA-SYSTEM # springboot-rest-template-feign为注册到Eureka上的服务名
    api:
      path: /apis/**
      service-id: ROUNA-SYSTEM
#      url: http://localhost:8081
    web-app:
      path: /**
      stripPrefix: false
      url: http://localhost:8080

#ribbon:
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule # 配置服务端负载均衡策略